CREATE TABLE IF NOT EXISTS print_jobs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id INT NOT NULL,
  store_id INT NOT NULL,
  token_id INT NOT NULL,
  order_id INT NOT NULL,
  public_id VARCHAR(64) NULL,
  job_name VARCHAR(255) NOT NULL DEFAULT 'CRM Receipt',
  pdf_base64 LONGTEXT NOT NULL,
  status ENUM('pending', 'processing', 'done', 'failed') NOT NULL DEFAULT 'pending',
  attempts INT NOT NULL DEFAULT 0,
  last_error TEXT NULL,
  locked_at DATETIME NULL,
  acked_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_print_job_order (tenant_id, store_id, order_id),
  KEY idx_print_jobs_queue (tenant_id, store_id, token_id, status, id),
  KEY idx_print_jobs_status (status, locked_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
